### PR TITLE
[#43] Switched to `mariadb-10.11-drupal` upstream image.

### LINKED ISSUE #43: Move to the new Lagoon image
`uselagoon/mariadb-drupal` -> `uselagoon/mariadb-10.4-drupal`

See https://gist.github.com/tobybellwood/d391f2a68f7e96264e5fe21803ca4ab1

### PR DESCRIPTION
**Pull request by AlexSkrypnyk**
Closes #43

## Changed

1. Moved the data dir to `/home/db-data`
2. Updated tests to build only for `linux/amd64`
3. Added fixture DB file.
4. Updated test assertions.

### CODE REVIEW

**Comment by AlexSkrypnyk** [comment]
@tannguyen04 
can you please update this to `mariadb-10.11-drupal` and try to fix this

**Comment by tannguyen04** [comment]
Hi @AlexSkrypnyk 
I tried really hard to fix the failure but not success. But I found something may help you to solve the problem quickly or advise the next step.

1. When we switch to mariadb-10.11-drupal, the base image use MariaDB 10.11.6. But the Dockerfile.seed is using drevops/mariadb-drupal-data:latest which use MariaDB 10.4.25.  => the stage 3 test image is failed because the https://github.com/drevops/mariadb-drupal-data/blob/main/seed-db.sh#L164

The SEED_IMAGE should be base image instead of drevops/mariadb-drupal-data:latest. So I made the changes like this and step 3 test image is passed https://github.com/drevops/mariadb-drupal-data/pull/44/files#diff-f29ded04891d5db51b96a02d4fa376df62b93ebecd2b909424d9d2a64c664989R84-R87
2. The new failure is coming when test force mysql upgrade when run the container under user 1000.
https://github.com/drevops/mariadb-drupal-data/blob/main/tests/bats/data.bats#L112
Since MariaDB 10.6 introduce new sys directory under data directory then something wrong with permission under sys.

`Phase 3/8: Running 'mysql_fix_privilege_tables'
ERROR 35 (HY000) at line 819: Warning: Can't copy ownership for file './sys/version.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2299: Warning: Can't copy ownership for file './sys/schema_object_overview.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2318: Warning: Can't copy ownership for file './sys/schema_auto_increment_columns.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2366: Warning: Can't copy ownership for file './sys/x@0024schema_flattened_keys.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2391: Warning: Can't copy ownership for file './sys/schema_redundant_indexes.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2450: Warning: Can't copy ownership for file './sys/ps_check_lost_instrumentation.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2463: Warning: Can't copy ownership for file './sys/latest_file_io.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2488: Warning: Can't copy ownership for file './sys/x@0024latest_file_io.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2513: Warning: Can't copy ownership for file './sys/io_by_thread_by_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2545: Warning: Can't copy ownership for file './sys/x@0024io_by_thread_by_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2577: Warning: Can't copy ownership for file './sys/io_global_by_file_by_bytes.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2603: Warning: Can't copy ownership for file './sys/x@0024io_global_by_file_by_bytes.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2629: Warning: Can't copy ownership for file './sys/io_global_by_file_by_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2655: Warning: Can't copy ownership for file './sys/x@0024io_global_by_file_by_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2681: Warning: Can't copy ownership for file './sys/io_global_by_wait_by_bytes.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2717: Warning: Can't copy ownership for file './sys/x@0024io_global_by_wait_by_bytes.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2753: Warning: Can't copy ownership for file './sys/io_global_by_wait_by_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2791: Warning: Can't copy ownership for file './sys/x@0024io_global_by_wait_by_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2829: Warning: Can't copy ownership for file './sys/memory_by_user_by_current_bytes.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2850: Warning: Can't copy ownership for file './sys/x@0024memory_by_user_by_current_bytes.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2871: Warning: Can't copy ownership for file './sys/memory_by_host_by_current_bytes.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2892: Warning: Can't copy ownership for file './sys/x@0024memory_by_host_by_current_bytes.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2913: Warning: Can't copy ownership for file './sys/memory_by_thread_by_current_bytes.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2941: Warning: Can't copy ownership for file './sys/x@0024memory_by_thread_by_current_bytes.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2969: Warning: Can't copy ownership for file './sys/memory_global_by_current_bytes.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 2992: Warning: Can't copy ownership for file './sys/x@0024memory_global_by_current_bytes.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3015: Warning: Can't copy ownership for file './sys/memory_global_total.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3024: Warning: Can't copy ownership for file './sys/x@0024memory_global_total.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3033: Warning: Can't copy ownership for file './sys/schema_index_statistics.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3064: Warning: Can't copy ownership for file './sys/x@0024schema_index_statistics.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3095: Warning: Can't copy ownership for file './sys/x@0024ps_schema_table_statistics_io.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3123: Warning: Can't copy ownership for file './sys/schema_table_statistics.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3172: Warning: Can't copy ownership for file './sys/x@0024schema_table_statistics.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3359: Warning: Can't copy ownership for file './sys/schema_tables_with_full_table_scans.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3377: Warning: Can't copy ownership for file './sys/x@0024schema_tables_with_full_table_scans.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3395: Warning: Can't copy ownership for file './sys/schema_unused_indexes.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3413: Warning: Can't copy ownership for file './sys/schema_table_lock_waits.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3467: Warning: Can't copy ownership for file './sys/x@0024schema_table_lock_waits.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3521: Warning: Can't copy ownership for file './sys/statement_analysis.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3575: Warning: Can't copy ownership for file './sys/x@0024statement_analysis.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3629: Warning: Can't copy ownership for file './sys/statements_with_errors_or_warnings.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3659: Warning: Can't copy ownership for file './sys/x@0024statements_with_errors_or_warnings.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3689: Warning: Can't copy ownership for file './sys/statements_with_full_table_scans.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3728: Warning: Can't copy ownership for file './sys/x@0024statements_with_full_table_scans.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3767: Warning: Can't copy ownership for file './sys/x@0024ps_digest_avg_latency_distribution.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3779: Warning: Can't copy ownership for file './sys/x@0024ps_digest_95th_percentile_by_avg_us.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3796: Warning: Can't copy ownership for file './sys/statements_with_runtimes_in_95th_percentile.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3838: Warning: Can't copy ownership for file './sys/x@0024statements_with_runtimes_in_95th_percentile.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3880: Warning: Can't copy ownership for file './sys/statements_with_sorting.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3915: Warning: Can't copy ownership for file './sys/x@0024statements_with_sorting.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3950: Warning: Can't copy ownership for file './sys/statements_with_temp_tables.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 3981: Warning: Can't copy ownership for file './sys/x@0024statements_with_temp_tables.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4012: Warning: Can't copy ownership for file './sys/user_summary_by_file_io_type.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4032: Warning: Can't copy ownership for file './sys/x@0024user_summary_by_file_io_type.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4052: Warning: Can't copy ownership for file './sys/user_summary_by_file_io.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4068: Warning: Can't copy ownership for file './sys/x@0024user_summary_by_file_io.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4084: Warning: Can't copy ownership for file './sys/user_summary_by_statement_type.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4113: Warning: Can't copy ownership for file './sys/x@0024user_summary_by_statement_type.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4142: Warning: Can't copy ownership for file './sys/user_summary_by_statement_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4169: Warning: Can't copy ownership for file './sys/x@0024user_summary_by_statement_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4196: Warning: Can't copy ownership for file './sys/user_summary_by_stages.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4215: Warning: Can't copy ownership for file './sys/x@0024user_summary_by_stages.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4234: Warning: Can't copy ownership for file './sys/user_summary.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4270: Warning: Can't copy ownership for file './sys/x@0024user_summary.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4306: Warning: Can't copy ownership for file './sys/host_summary_by_file_io_type.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4326: Warning: Can't copy ownership for file './sys/x@0024host_summary_by_file_io_type.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4346: Warning: Can't copy ownership for file './sys/host_summary_by_file_io.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4362: Warning: Can't copy ownership for file './sys/x@0024host_summary_by_file_io.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4378: Warning: Can't copy ownership for file './sys/host_summary_by_statement_type.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4407: Warning: Can't copy ownership for file './sys/x@0024host_summary_by_statement_type.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4436: Warning: Can't copy ownership for file './sys/host_summary_by_statement_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4463: Warning: Can't copy ownership for file './sys/x@0024host_summary_by_statement_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4490: Warning: Can't copy ownership for file './sys/host_summary_by_stages.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4509: Warning: Can't copy ownership for file './sys/x@0024host_summary_by_stages.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4528: Warning: Can't copy ownership for file './sys/host_summary.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4563: Warning: Can't copy ownership for file './sys/x@0024host_summary.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4598: Warning: Can't copy ownership for file './sys/wait_classes_global_by_avg_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4621: Warning: Can't copy ownership for file './sys/x@0024wait_classes_global_by_avg_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4644: Warning: Can't copy ownership for file './sys/wait_classes_global_by_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4667: Warning: Can't copy ownership for file './sys/x@0024wait_classes_global_by_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4690: Warning: Can't copy ownership for file './sys/waits_by_user_by_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4713: Warning: Can't copy ownership for file './sys/x@0024waits_by_user_by_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4736: Warning: Can't copy ownership for file './sys/waits_by_host_by_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4758: Warning: Can't copy ownership for file './sys/x@0024waits_by_host_by_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4780: Warning: Can't copy ownership for file './sys/waits_global_by_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4800: Warning: Can't copy ownership for file './sys/x@0024waits_global_by_latency.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4872: Warning: Can't copy ownership for file './sys/processlist.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 4957: Warning: Can't copy ownership for file './sys/x@0024processlist.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 5042: Warning: Can't copy ownership for file './sys/session.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 5049: Warning: Can't copy ownership for file './sys/x@0024session.frm-' (Errcode: 1 "Operation not permitted")
ERROR 35 (HY000) at line 5056: Warning: Can't copy ownership for file './sys/session_ssl_status.frm-' (Errcode: 1 "Operation not permitted")
FATAL ERROR: Upgrade failed`

**Comment by AlexSkrypnyk** [comment]
@tannguyen04 
Thank you for working on this

> When we switch to mariadb-10.11-drupal, the base image use MariaDB 10.11.6. But the Dockerfile.seed is using drevops/mariadb-drupal-data:latest which use MariaDB 10.4.25. => the stage 3 test image is failed because the https://github.com/drevops/mariadb-drupal-data/blob/main/seed-db.sh#L164
The SEED_IMAGE should be base image instead of drevops/mariadb-drupal-data:latest. So I made the changes like this and step 3 test image is passed https://github.com/drevops/mariadb-drupal-data/pull/44/files#diff-f29ded04891d5db51b96a02d4fa376df62b93ebecd2b909424d9d2a64c664989R84-R87
For test, the seed image should be our freshly built image.
For end user, the seed image in `Dockerfile.seed`, should still be the `drevops/mariadb-drupal-data:latest` (the latest stable image of **this** repo).

> 2. The new failure is coming when test force mysql upgrade when run the container under user 1000.
https://github.com/drevops/mariadb-drupal-data/blob/main/tests/bats/data.bats#L112
Since MariaDB 10.6 introduce new sys directory under data directory then something wrong with permission under sys.

Is this locally or in CI?
Can you please remove `1000` and try re-running this in CI

**Comment by tannguyen04** [comment]
Hi @AlexSkrypnyk 
https://app.circleci.com/pipelines/github/drevops/mariadb-drupal-data/253/workflows/35a71904-347b-471d-93e7-b2c0246dba3c/jobs/270
The test is passed but failed on deploy image step.

**Pull request merged**
